### ISSUE TITLE
Review documentation

### ISSUE THREAD

**Issue by jakobj** [jakobj/nest-simulator#34]
Documentation in source files: `ConnectionManager`, `SourceTable`, `TargetTable`, `EventDeliveryManager`
Make sure new 5g classes/functions are documented, and outdated 4g documentation is removed.

Make sure user documentation is up to date

**Comment by jakobj** [comment]
@stinebuu @hakonsbm

**Comment by hakonsbm** [comment]
@jakobj Now that #63 is merged, can this be closed?

**Comment by jakobj** [comment]
yes, thank you again for your work. closing.
