### ISSUE TITLE
Duplicate PRs with SymmetricBernoulliBuilder

### ISSUE THREAD

**Issue by stinebuu** [jakobj/nest-simulator#61]
Hi! There seems to be two PRs towards NEST master containing the `SymmetricBernoulliBuilder`. The 5g nest#920 PR, and nest#873. nest#873 is partially reviewed, but is not scheduled to be part of NEST2.16.

**Comment by jakobj** [comment]
i suggest to close https://github.com/nest/nest-simulator/pull/873 in favor of https://github.com/nest/nest-simulator/pull/920. will make sure all changes discussed in https://github.com/nest/nest-simulator/pull/873 enter https://github.com/nest/nest-simulator/pull/920

**Comment by jakobj** [comment]
addressed by #96

**Comment by jakobj** [comment]
closed by #96
