### ISSUE TITLE
Assertion thrown when simulating with ginzburg_neuron and mcculloch_pitts_neuron

### ISSUE THREAD

**Issue by stinebuu** [jakobj/nest-simulator#75]
Running the code snippet
```
import nest

nest.ResetKernel()

n1 = nest.Create("ginzburg_neuron")
n2 = nest.Create("mcculloch_pitts_neuron")

nest.Connect(n1, n2, syn_spec={"weight": 1.0})

nest.Simulate(100.)
```
leads to an assertion being thrown. I discovered this while looking at the examples, and saw that `correlospinmatrix_detector_two_neuron.py` failed.

The assertion happens because of the `handle( SpikeEvent& e )` function to the `binary_neuron`, which both `ginzburg_neuron` and `mcculloch_pitts_neuron` are derived from. The `handle` function calls
```
long gid = e.get_sender_gid();
```
which calls
```
inline index
Event::get_sender_gid( void ) const
{
  assert( sender_gid_ > 0 );
  return sender_gid_;
}
```
and the `sender_gid_` is set to be 0 for some reason. The strange thing is that `EventDeliveryManager` actually set the correct `sender_gid` in its [`send` function](https://github.com/jakobj/nest-simulator/blob/5g/nestkernel/event_delivery_manager_impl.h#L64), but I haven't figured out where things go wrong.

I can make a regression test for this and try to look more into it.

**Comment by jakobj** [comment]
fixed by #76
